### ISSUE TITLE
Practica de Objetos 3d con ubicación GPS

### ISSUE THREAD

**Issue by Itzelzun** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-francisco#2]
[Practica de Objetos 3d con ubicación GPS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-francisco/files/6766026/Practica.de.Objetos.3d.con.ubicacion.GPS.pdf)

**Comment by AxayacatlS** [comment]
Calificación: 20 Excelente trabajo

**Comment by josealfredo79** [comment]
Deben de hacer la descripción de la practica

**Comment by josealfredo79** [comment]
Bien hecho y revisado
